/* 🤖 this file was generated by svg-to-ts*/
export * from './dinosaur-icons/dinosaurIcon-artist.icon';
export * from './dinosaur-icons/dinosaurIcon-birthday.icon';
export * from './dinosaur-icons/dinosaurIcon-chef.icon';
export * from './dinosaur-icons/dinosaurIcon-sleep.icon';
export * from './dinosaur-icons/dinosaurIcon-space.icon';
export * from './dinosaur-icons/dinosaur-icons';
